project_id = "wcuxqopfcgivypbiynjp"

[functions.send-email-notification]
verify_jwt = true

[functions.process-notifications]
verify_jwt = false

[functions.notification-scheduler]
verify_jwt = false

[functions.send-team-invitation]
verify_jwt = true

[functions.accept-team-invitation]
verify_jwt = false

[functions.stripe-whoami]
verify_jwt = false

[functions.sync-pricing]
verify_jwt = false